/**
 * Presentation abstracts curated from the BIO2026 programme booklet.
 * session tags: 1A, 1B, 2A, 2B, flash
 */

export type AbstractSession = "1A" | "1B" | "2A" | "2B" | "flash";

export type Abstract = {
  slug: string;
  title: string;
  authors: string;
  affiliations: string;
  email?: string;
  session: AbstractSession;
  keywords: string[];
  body: string;
};

export const sessionLabels: Record<AbstractSession, string> = {
  "1A": "Session 1A — Human Landscapes",
  "1B": "Session 1B — Pathogen Landscapes",
  "2A": "Session 2A — Computation Landscapes",
  "2B": "Session 2B — Ecological Landscapes",
  flash: "Session 3 — Flash talks",
};

export const abstracts: Abstract[] = [
  {
    slug: "phylogenetic-age-mitochondrial-heteroplasmy",
    title: "Phylogenetic age is associated with mitochondrial heteroplasmy in African and diaspora populations",
    authors: "Dayna Adrienne Croock*, Elouise Kroon, Devon Allies, André G. Loxton, Marlo Möller, Caitlin Uren, Desiree C. Petersen",
    affiliations: "SAMRC Centre for Tuberculosis Research / MBHG, Stellenbosch University; Centre for Bioinformatics and Computational Biology, Stellenbosch University; Genomics for Health in Africa; NITheCS",
    email: "dayna@sun.ac.za",
    session: "1A",
    keywords: ["mitochondrial DNA", "heteroplasmy", "phylogenetic age", "African genomes"],
    body: `Background: Mitochondrial DNA (mtDNA) heteroplasmy—the co-existence of multiple mtDNA variants within an individual—has been linked to ageing, disease susceptibility, and cellular dysfunction. However, the evolutionary and population-level factors governing heteroplasmy burden remain poorly understood. Recent work in green sea turtles demonstrated that individuals carrying phylogenetically derived mtDNA haplotypes accumulate more heteroplasmic variants than those carrying ancestral haplotypes, suggesting that lineage age may influence heteroplasmy burden. Here, we test whether a similar phylogenetic age effect exists in humans using whole mitochondrial genome sequencing data from 1,306 individuals representing African and diaspora populations. Using negative binomial and Poisson generalised linear models with L0—the most ancestral human mtDNA macrohaplogroup—as the reference, we find that carriers of L1, L2, and L3 haplogroups exhibit significantly higher heteroplasmy counts (incidence rate ratios 2.71–3.41, all FDR-adjusted p < 10⁻³⁹). This pattern persists after controlling for broad geographic region and is replicated in a diaspora-only subset with shared demographic history. Importantly, using calibrated sub-haplogroup age estimates, we identify a significant negative relationship between sub-haplogroup age and heteroplasmy burden within L0 itself (IRR = 0.978 per thousand years, p = 3.8 × 10⁻¹⁴). Each additional 1,000 years of lineage age is associated with approximately 2.2% fewer heteroplasmic variants. This within-lineage gradient provides strong evidence that phylogenetic age contributes to shaping mtDNA heteroplasmy burden in humans.`,
  },
  {
    slug: "transcriptomic-interferon-thp1",
    title: "Transcriptomic characterisation of differentiation-driven priming of the interferon-α response in THP-1 macrophages",
    authors: "Boithuso Phale*, Prumohdya D. Muamba, Vanessa Meyer, Nikki L. Gentle",
    affiliations: "School of Molecular and Cell Biology, University of the Witwatersrand",
    email: "2451444@students.wits.ac.za",
    session: "1A",
    keywords: ["macrophages", "interferon", "ISGs", "CAGE-seq", "differentiation"],
    body: `Monocytes and macrophages are important coordinators of the innate response to infectious disease. During infection, monocytes are recruited to tissues where they differentiate into macrophages, which mount interferon (IFN)-driven antiviral responses through the expression of IFN-stimulated genes (ISGs). While ISG expression is classically attributed to IFN signalling, the contribution of monocyte-to-macrophage differentiation to priming this response remains poorly understood. Differential gene expression with DESeq2 on RNA-seq from THP-1 macrophages differentiated with PMA and stimulated with IFN-α2 identified 978 significantly differentially expressed ISGs. Cap Analysis of Gene Expression (CAGE-seq) across 96 hours of differentiation revealed progressive ISG induction, increasing from 24 differentially expressed ISGs early to 173 ISGs by 24 hours without cytokine stimulation. Hierarchical clustering revealed early-induced and sustained, late-induced, and transiently induced ISGs. Motif-enrichment analysis identified EGR1, EGR2, SP1, and IRF8 as potential key regulators. Together, these findings suggest that differentiation progressively rewires ISG expression through distinct regulatory waves that prime macrophages for a robust IFN response.`,
  },
  {
    slug: "ccr5-hiv1-susceptibility",
    title: "CCR5 regulatory variants and novel loci associated with susceptibility to HIV-1 infection in Sub-Saharan African populations",
    authors: "Isabel du Randt* and co-authors (NORA / Sydney Brenner Institute consortium)",
    affiliations: "Sydney Brenner Institute for Molecular Bioscience, University of the Witwatersrand and collaborating institutions across South and East Africa",
    email: "fourieisabel1@gmail.com",
    session: "1A",
    keywords: ["HIV-1", "GWAS", "CCR5", "African ancestry"],
    body: `Background: HIV-1 infection remains a major global health challenge, with Sub-Saharan Africa bearing the highest disease burden. Most GWAS of host susceptibility have been conducted in non-African populations. Methods: We conducted the largest GWAS to date of susceptibility to HIV-1 infection in individuals of SSA ancestry, including 3,069 HIV-1 positive cases and 14,291 HIV-1 negative controls from South and East Africa. Fine-mapping and colocalisation with SABR blood eQTLs evaluated functional mechanisms. Results: Three independent loci reached genome-wide significance: rs2040388 and rs2227010 on chromosome 3 (CCR5AS / upstream of CCR5), rs112358207 on chromosome 1 (ESRRG), and rs113298445 on chromosome 8 (INTS9). The chromosome 3 signal colocalised with eQTL variants for CCR5AS expression. Although CCR5Δ32 is absent in African populations, alternative variants in the CCR5 regulatory region may modulate susceptibility. Conclusions: This study revealed both shared and population-specific genetic determinants of HIV-1 susceptibility and underscores the central role of CCR5 regulation in host defence.`,
  },
  {
    slug: "tb-relapse-sex-specific-signature",
    title: "Sex-specific gene expression signatures as biomarkers in predicting tuberculosis relapse",
    authors: "Bongani Mnyandli*, Anandi Bierman, Gerhard Walzl",
    affiliations: "Stellenbosch University, Stellenbosch, South Africa",
    email: "nzimandebongani05@gmail.com",
    session: "1A",
    keywords: ["tuberculosis", "relapse", "biomarkers", "machine learning"],
    body: `Background: Tuberculosis (TB) relapse after treatment completion remains a major challenge, with limited reliable biomarkers and important sex-dependent biological differences. Methods: Gene expression data from the PREDICT-TB cohort were analysed with a three-stage machine learning feature selection pipeline on the male subset. The final minimal gene panel was evaluated with Random Forest and XGBoost using AUC, sensitivity, and specificity via repeated k-fold cross-validation and external validation. Results: A 7-gene signature (ENTPD2, KANK1, ANAPC13, PI4K2A, INTS1, ZNF439 and NFATC2IP-AS1) discriminated relapsed from cured patients internally; RF yielded AUC = 0.9656. Performance declined on external cohorts, indicating limited generalizability. Conclusion: The signature is a strong mechanistic hypothesis for male-specific relapse susceptibility, but cross-cohort harmonization and a female-specific signature are needed for clinical translation.`,
  },
  {
    slug: "ahsv-ns5-localisation",
    title: "Characterisation of the subcellular localisation of African horse sickness virus non-structural protein NS5",
    authors: "Nhlakanipho Mtambo*, Eshchar Mizrachi, Vida van Staden",
    affiliations: "Department of Biochemistry, Genetics and Microbiology, University of Pretoria",
    email: "nipho.mtambo@up.ac.za",
    session: "1B",
    keywords: ["AHSV", "NS5", "orbivirus", "subcellular localisation"],
    body: `African horse sickness virus (AHSV) is an economically important orbivirus affecting equids throughout sub-Saharan Africa. Genome segment 10 encodes NS3 and an alternative +1 ORF predicted to encode non-structural protein NS5. In silico analysis of 105 unique NS5 ORFs predicted conserved N-terminal mitochondrial targeting features and a putative nuclear localisation signal. Mutagenesis suggested arginine residues at positions 21 and 22 contribute to mitochondrial targeting scores. Recombinant baculovirus constructs of wild-type and mutant NS5 fused to Strep-tag, Twin-Strep-tag, or eGFP were expressed in Sf9 cells. Confocal microscopy showed Strep-tagged NS5 predominantly nuclear, while eGFP fusions showed mixed nuclear and partial mitochondrial localisation, supporting dual organelle localisation and informing future functional studies.`,
  },
  {
    slug: "ehrlichia-ruminantium-mlst",
    title: "Genetic diversity of Ehrlichia ruminantium based on multilocus sequence typing of isolates from indigenous goats and Amblyomma hebraeum ticks",
    authors: "Xolile Nuse*, H.C. Steyn, M.A. Van Der Nest, K. Hadebe, F.C. Muchadeyi, E.F. Dzomba",
    affiliations: "University of KwaZulu-Natal; Agricultural Research Council; University of Pretoria",
    email: "xolilenuse@gmail.com",
    session: "1B",
    keywords: ["E. ruminantium", "heartwater", "MLST", "genetic diversity"],
    body: `Heartwater, caused by Ehrlichia ruminantium and transmitted by Amblyomma ticks, remains a major constraint on ruminant production in sub-Saharan Africa. This study investigated genetic diversity of isolates from South African indigenous goats and A. hebraeum ticks using MLST. Screening of 381 goat blood and 70 tick samples yielded 14.7% and 44.3% positives respectively. Sequencing of gltA, groEL, sucA2, and pCS20 identified 11 unique sequence types among 44 sequences (haplotype diversity 0.77). Phylogenetic analyses revealed multiple co-circulating lineages related to Gardel, Kümm2, and Grootvallei, alongside divergent local genotypes. Host-associated structuring was weak (FST = 0.0247), with 97% of variation within host groups, supporting a shared goat–tick transmission system.`,
  },
  {
    slug: "tps-anopheles-insecticides",
    title: "Genomic surveillance of trehalose-6-phosphate synthase in Anopheles gambiae: a promising target for next-generation insecticides",
    authors: "Mercy Bella-Omunagbe*, Nina Ghislaine Yensii, Abiodun H. Adebayo, Shalom N. Chinedu",
    affiliations: "Department of Biochemistry / CApIC-ACE, Covenant University, Ota",
    email: "mercy.bella-omunagbepgs@stu.cu.edu.ng",
    session: "1B",
    keywords: ["Anopheles", "TPS", "insecticide targets", "Ag1000G"],
    body: `Background: Insecticide resistance in Anopheles gambiae threatens malaria control. Trehalose-6-phosphate synthase (TPS) is essential for insect survival, absent in humans, and a promising insecticide target. Methods: Ag1000G Phase 3.0 whole-genome data from 19 African countries were analysed for SNPs, allele frequencies, diversity, Tajima's D, LD, and functional impact (SIFT/PROVEAN). Results: 4590 TPS variants included 459 non-synonymous mutations; 19 occurred at appreciable frequencies and were generally rare, geographically restricted, and species-specific. About 32% of variants were predicted deleterious. Low nucleotide diversity and negative Tajima's D indicate purifying selection. Conclusion: TPS appears genetically stable across the An. gambiae complex and is a promising molecular target pending functional validation.`,
  },
  {
    slug: "fungal-biocide-anopheles",
    title: "Isolation and characterization of biocide producing fungus against Anopheles mosquitoes from pesticide factory effluents",
    authors: "Tariku Feyisa Wakjira*, Musin Kelel Abas, Misrak Kebede, Kejelcha Fikadu, Tirsit Tibebu",
    affiliations: "Addis Ababa Science and Technology University; Dembi Dollo University; Holota National Agricultural Biotechnology Research Centre",
    email: "tarefk2018@gmail.com",
    session: "1B",
    keywords: ["biocide", "fungi", "mosquito", "larvae", "pesticide"],
    body: `Background: Mosquito insecticide resistance drives the need for eco-friendly biocontrol agents. This study isolated and characterised fungal biocides from pesticide-contaminated environments. Methodology: Effluent isolates were characterised morphologically, biochemically and molecularly, screened for spore production and larvicidal activity, profiled by GC-MS, and evaluated with molecular docking. Results: Thirty isolates were obtained; W1 and W4 showed strong potential with larval mortality from 6.67% to 100%. W1 matched Penicillium crustosum (99%) and W4 Rhizopus arrhizus (100%). GC-MS identified 33 and 29 compounds respectively; docking predicted strong affinity for several compounds including Phenol, 2-(1-phenylethyl)-. Conclusion: These fungal isolates are promising biocontrol candidates pending culture optimisation and formulation studies.`,
  },
  {
    slug: "gnn-mirna-mrna-breast-cancer",
    title: "Graph neural network-based discovery of miRNA-mRNA regulatory interactions in breast cancer",
    authors: "Nothando Gama*, Hocine Bendou",
    affiliations: "SANBI, SA Medical Research Council Bioinformatics Unit, University of the Western Cape",
    email: "nothandograce82@gmail.com",
    session: "2A",
    keywords: ["graph neural networks", "miRNA", "breast cancer", "link prediction"],
    body: `Breast cancer mortality is linked to dysregulation of miRNA-mediated gene regulation. This study developed a Heterogeneous Graph Transformer (HGT) link-prediction framework integrating miRTarBase interactions with TCGA-BRCA (and TCGA-OV to expand coverage). The model achieved accuracy 82%, AUC-ROC 90%, AUC-PRC 80%, F1 75%, and MCC 62%. High-confidence novel predictions included hsa-miR-4775 targeting SMAD4, ABCA1, and ZMAT3, and hsa-miR-520d-5p targeting BMPR2—targets implicated in TGF-β signalling, EMT, tumour suppression, and p53-mediated apoptosis. Graph-based deep learning can accelerate discovery of miRNA-mediated mechanisms for experimental validation.`,
  },
  {
    slug: "cervical-cancer-methylation-tme",
    title: "Reconstructing cervical cancer tumour microenvironment states from DNA methylation profiles using a machine learning framework",
    authors: "Saltiel Hamese*, Mutsa Takundwa, Earl Prinsloo, Deepak Balaji Thimiri Govinda Raj",
    affiliations: "CSIR Synthetic Biology and Precision Medicine Centre, Pretoria; Biotechnology Innovation Centre, Rhodes University",
    email: "hamesesaltiel@gmail.com",
    session: "2A",
    keywords: ["cervical cancer", "DNA methylation", "tumour microenvironment", "machine learning"],
    body: `Background: Cervical cancer burden is high in LMICs, worsened by HPV and HIV co-infection, yet frameworks linking bulk epigenomic data to tumour microenvironment (TME) states remain limited. Methods: A DNA methylation-based ML framework integrates feature selection, deconvolution, unsupervised clustering, and predictive modelling to reconstruct TME states. Results: Four distinct TME states were identified, differing in immune activity, stroma, epithelial differentiation, and proliferation. HIV-associated perturbations were largely restricted to immune-inflamed tumours. Inferred states enabled alignment of patient tumours with cell-line models. Conclusions: The framework supports biomarker discovery, risk stratification, and bridging patient biology with preclinical models.`,
  },
  {
    slug: "amr-okavango-ngamiland",
    title: "Surveillance and monitoring of antimicrobial-resistant human pathogenic and zoonotic bacteria in the Ngamiland and Okavango Delta",
    authors: "Patience Motshosi*, Kabo Baruti",
    affiliations: "Botswana Harvard Health Partnership; Okavango Research Institute, University of Botswana",
    email: "patiencemotshosi@gmail.com",
    session: "2B",
    keywords: ["AMR", "metagenomics", "Okavango", "freshwater"],
    body: `Antimicrobial resistance is a critical global health threat. Surface water from eight Okavango/Ngamiland sites was sequenced (Illumina NextSeq2000); taxonomy used Kraken2 and ARGs AMRFinder. Seasonal variation influenced salinity and conductivity. Abundant pathogens included Acinetobacter lwoffii and A. johnsonii; clinically significant zoonotic taxa were detected at low abundance. The resistome was dominated by efflux genes MexF and MexB alongside β-lactamase TEM-116. Co-detection of TEM-116 and transposase TniB raises HGT concerns. Freshwater metagenomic surveillance is a valuable early-warning system for AMR in Botswana and comparable LMICs.`,
  },
  {
    slug: "spotted-hyena-genomics",
    title: "Assessing the genetic diversity and structure of spotted hyena (Crocuta crocuta) populations across Africa",
    authors: "Kagisho Dibakoane*, Yoshan Moodley, Michael Westbury",
    affiliations: "Department of Zoology, University of Venda; Technical University of Denmark",
    email: "kagisoralph@gmail.com",
    session: "2B",
    keywords: ["spotted hyena", "population genomics", "conservation", "Africa"],
    body: `Whole-genome and RAD-seq data from 55 spotted hyenas across sub-Saharan Africa quantified diversity, structure, and gene flow. Heterozygosity ranged from 0.1485 to 0.3688. Three major clusters (western, eastern, southern Africa) subdivided into five regional groups. D-statistics indicated gene flow especially between eastern and southern populations; the western cluster was more differentiated with lowest diversity. Patterns parallel other large African carnivores and reflect biogeography plus anthropogenic fragmentation. Results highlight conservation strategies that restore connectivity to western populations.`,
  },
  {
    slug: "salmon-gut-microbiome-smoltification",
    title: "Temporal dynamics of the gut microbiome during smoltification in Atlantic salmon (Salmo salar)",
    authors: "Badrodin M*, Difford G, Rhode C",
    affiliations: "Department of Genetics, Stellenbosch University; Institute of Animal and Aquaculture Sciences, NMBU, Norway",
    email: "23563036@sun.ac.za",
    session: "2B",
    keywords: ["Atlantic salmon", "gut microbiome", "smoltification", "16S"],
    body: `Smoltification enables seawater adaptation in Atlantic salmon, yet gut microbiome temporal dynamics remain poorly understood. Gut communities from n = 162 fish across smoltification were profiled by 16S rRNA sequencing (DADA2/Phyloseq). Alpha diversity varied significantly among weeks; beta diversity (Bray–Curtis PERMANOVA) showed temporal differentiation consistent with ecological succession. Bacillota and Pseudomonadota may serve as indicators of seawater adaptation. Microbiome composition is a complex quantitative trait shaped by development and environment, with implications for salmon health at sea.`,
  },
  {
    slug: "dematophora-mating-strategy",
    title: "Unravelling the elusive mating strategy of Dematophora necatrix: a combined genomic and physiological approach",
    authors: "Annabel Norval*, Markus Wilken, Noëlani van den Berg",
    affiliations: "FABI / Avocado Research Programme, University of Pretoria",
    email: "annabel.norval@up.ac.za",
    session: "2B",
    keywords: ["Dematophora necatrix", "mating-type", "fungal genomics", "avocado"],
    body: `Sexual reproduction in pathogenic ascomycetes is governed by the MAT1 locus, but canonical MAT1 genes appear absent across sequenced Xylariales, and D. necatrix mating strategy is unresolved. This study combined funannotate genome annotation, HMMER/InterProScan/phylogenetics/AlphaFold3 structural comparison, and controlled crossing of eight single-ascospore isolates with Illumina WGS. The dual approach yielded candidate mating-type genes via a novel methodology, genome-wide Xylariales annotations, and foundational insights into D. necatrix mating to aid pathogen control.`,
  },
  {
    slug: "southern-bald-ibis-genome",
    title: "Advancing avian genomics: a de novo assembly pipeline for a high-quality Southern Bald Ibis (Geronticus calvus) reference genome",
    authors: "Ashley Mortimer*, Anri van Wyk, Arrie Klopper, Paulette Bloomer",
    affiliations: "Molecular Ecology and Evolution Programme, University of Pretoria",
    email: "u21530794@tuks.co.za",
    session: "flash",
    keywords: ["Southern Bald Ibis", "reference genome", "ONT", "conservation"],
    body: `The Southern Bald Ibis is a near-threatened southern African species lacking a reference genome. ONT long-read sequencing and a de novo pipeline (trim, filter, assemble, map, polish, haplotig purge, scaffold) produced a 1.218 Gb assembly (464 contigs, N50 25.97 Mb, 99.4% BUSCO). The reference-level genome enables future population and landscape genomics for conservation.`,
  },
  {
    slug: "fasciola-schistosoma-diagnostics",
    title: "An immunoinformatics approach for cross-species diagnostics: validating a Fasciola gigantica surrogate antigen for Schistosoma haematobium detection",
    authors: "Adedayo O. Adesida*, Kabirat A. Suleiman, Stella A. Kayode, Oyetunde T. Oyeyemi",
    affiliations: "Institute of Genomics and Global Health, Redeemer's University; University of Medical Sciences, Ondo",
    email: "adesida19852@run.edu.ng",
    session: "flash",
    keywords: ["immunoinformatics", "schistosomiasis", "diagnostics", "surrogate antigen"],
    body: `Background: Sourcing S. haematobium antigens for RDTs is challenging; conserved epitopes in F. gigantica may enable surrogate biomarkers. Methods: Reciprocal BLASTp ortholog screening, secretory/surface filters, negative selection against the human proteome, HADDOCK docking and MM/GBSA validation. Results: A SAFE ortholog pair mapped to the Ly-6/uPAR/CD59 family with a conserved 23-aa structural core; docking confirmed high-affinity antibody binding. Conclusion: The Fasciola surrogate target supports next-generation RDT development without host autoantibody cross-reactivity.`,
  },
  {
    slug: "attention-localization-brain-mri",
    title: "Does multi-task supervision teach a classifier where to look? A quantitative attention-localization study in brain tumor MRI",
    authors: "Tisetso Letuka*, Amukelani Mtshabi",
    affiliations: "Ezintsha, Wits Health Consortium, Faculty of Health Sciences, University of the Witwatersrand",
    email: "tisetsoletuka@gmail.com",
    session: "flash",
    keywords: ["explainability", "Grad-CAM", "multi-task learning", "brain MRI"],
    body: `Background: Multi-task learning is often assumed to improve clinically relevant attention, but this is largely unproven. Methodology: An EfficientNet-B4 multi-task model classified 30 pathology classes and predicted lesion coordinates on brain MRI; Grad-CAM++ centroids were compared to radiologist annotations on a 1,128-image validation set. The study quantitatively tests whether a lesion-localization head aligns diagnostic attention with true tumor centers across pathology classes.`,
  },
  {
    slug: "gut-microbiome-awi-gen",
    title: "The role of the gut microbiome in inflammation and multimorbidity in African populations: evidence from AWI-Gen",
    authors: "Aaron Y. Berkman*, Luicer A. Olubayo, Scott Hazelhurst",
    affiliations: "AWI-Gen 2 Microbiome Project / University of the Witwatersrand",
    session: "flash",
    keywords: ["gut microbiome", "AWI-Gen", "inflammation", "multimorbidity"],
    body: `Nested in the AWI-Gen 2 Microbiome Project (1,801 participants across Burkina Faso, Ghana, Kenya, and South Africa), this work links deep shotgun and long-read metagenomes with CRP and multimorbidity phenotypes. De novo MAGs recover African taxa missed by reference profilers; pre-specified microbial functions (SCFA, bile-acid, tryptophan–indole) are tested against CRP/multimorbidity, with long-read pangenomes resolving strain-level structure. Reproducible Nextflow workflows and preliminary findings will be presented.`,
  },
  {
    slug: "herv-detection-pipelines",
    title: "Impact of reference genome, alignment strategy, and quantification method on locus-specific HERV detection during monocyte-to-macrophage differentiation",
    authors: "Tebogo Phago*, Nikki Gentle, Vanessa Meyer",
    affiliations: "School of Molecular and Cell Biology, University of the Witwatersrand",
    email: "2436993@students.wits.ac.za",
    session: "flash",
    keywords: ["HERV", "RNA-seq", "GRCh38", "CHM13", "macrophage"],
    body: `HERVs comprise ~8% of the human genome but lack standardized locus-specific profiling workflows. THP-1 (and U937 validation) RNA-seq was aligned to GRCh38 and CHM13 with HISAT2/STAR and quantified with TE-locator/MAJEC. Mapping rates were similar (~89–93%), but quantification and DE results varied substantially by pipeline; CHM13 identified more DE HERV loci. A DE HERV near the IFNB1 promoter suggests a regulatory link to interferon signalling during macrophage differentiation.`,
  },
  {
    slug: "mdr-pseudomonas-biofilm",
    title: "Integrated phenotypic profiling and therapeutic target prioritization of clinical MDR Pseudomonas aeruginosa with biofilm-driven persistence",
    authors: "Sinethemba Yakobi*, Nontuthuko Maningi",
    affiliations: "School of Life Sciences, University of KwaZulu-Natal",
    email: "shyakobi@gmail.com",
    session: "flash",
    keywords: ["Pseudomonas aeruginosa", "biofilm", "MDR", "docking"],
    body: `Fifteen clinical MDR P. aeruginosa isolates were profiled for susceptibility and biofilm formation. Persistence-associated target PA0328 (AaaA) was modelled and docked against eight ligands; pimozide and EGCG ranked highest with distinct binding mechanisms. ADMET favoured pimozide for repurposing potential. The scalable framework integrates phenotypic, structural, and pharmacokinetic dimensions for target prioritization.`,
  },
  {
    slug: "dnbseq-t7-benchmarking",
    title: "Benchmarking DNBSEQ-T7 sequencing performance using Genome in a Bottle reference genomes: impact of library preparation strategies",
    authors: "Maano Malima*, Ansia van Coller, Setshaba Taukobong, Samira Ghoor, Nganea Nangammbi, Enrico Roode, Martin Naicker, Victoria Cole, Brigitte Glanzmann, Craig Kinnear, Nadia Carstens",
    affiliations: "SAMRC Genomics Platform and collaborating SAMRC / Stellenbosch / Wits units",
    email: "maano.malima@mrc.ac.za",
    session: "flash",
    keywords: ["DNBSEQ-T7", "GIAB", "library preparation", "variant calling"],
    body: `Background: Well-characterised references are essential for benchmarking sequencing platforms. Methods: Ashkenazi Jewish GIAB trio samples were sequenced on MGI DNBSEQ-T7 using PCR-free, FastFS DNA, and Universal DNA workflows (≥30×), processed with GATK, and evaluated against GIAB truth sets. Results: All workflows showed strong concordance; PCR-free performed best for indels and Mendelian violations. Conclusion: The public dataset supports DNBSEQ-T7 adoption for high-throughput genomics relevant to African diversity studies.`,
  },
  {
    slug: "dockvina-pipeline",
    title: "DockVina: an automated molecular docking pipeline for high throughput virtual screening",
    authors: "Siphamandla Mnakekeli Dlamini",
    affiliations: "",
    session: "2A",
    keywords: ["molecular docking", "virtual screening", "pipeline"],
    body: `Oral presentation describing DockVina, an automated molecular docking pipeline for high-throughput virtual screening. Full abstract text was not included in the distributed programme booklet PDF.`,
  },
  {
    slug: "taxonomic-binning-decision-trees",
    title: "Taxonomic binning of long-read DNA sequences by k-mer composition using decision tree classifiers",
    authors: "Bruhan Kyomuhendo",
    affiliations: "",
    session: "2A",
    keywords: ["long-read", "taxonomic binning", "k-mer", "decision trees"],
    body: `Oral presentation on taxonomic binning of long-read DNA sequences using k-mer composition and decision tree classifiers. Full abstract text was not included in the distributed programme booklet PDF.`,
  },
  {
    slug: "exserohilum-metabolites",
    title: "Comparative in silico prediction and characterisation of secondary metabolites of Exserohilum turcicum and Exserohilum rostratum",
    authors: "Catherina Kuetezang",
    affiliations: "",
    session: "flash",
    keywords: ["Exserohilum", "secondary metabolites", "in silico"],
    body: `Flash talk comparing in silico prediction and characterisation of secondary metabolites of Exserohilum turcicum and Exserohilum rostratum. Full abstract text was not included in the distributed programme booklet PDF.`,
  },
];

export function getAbstract(slug: string): Abstract | undefined {
  return abstracts.find((a) => a.slug === slug);
}
